apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingservice-app-settings
  namespace: tenant-boutique-prod
  labels:
    tenant: boutique
    app: boutique-app
    service: shippingservice
    environment: prod
data:
  app-settings.json: |
    {
      "schemaVersion": "platform.settings/v1",
      "platform": {
        "tenant": "boutique",
        "app": "boutique-app",
        "service": "shippingservice",
        "environment": "prod"
      },
      "keyVault": {
        "urlEnv": "PLATFORM_KEY_VAULT_URL",
        "secretMappings": [
          {
            "name": "appInsights",
            "env": "APPLICATIONINSIGHTS_CONNECTION_STRING",
            "secretName": "boutique-prod-appinsights-connection-string",
            "required": true
          }
        ]
      },
      "dependencies": {
        "services": {
        }
      },
      "features": {
      }
    }
