apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-frontend-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/frontend
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-cartservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/cartservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-checkoutservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/checkoutservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-currencyservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/currencyservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-emailservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/emailservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-paymentservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/paymentservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-productcatalogservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/productcatalogservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-recommendationservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/recommendationservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-shippingservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/shippingservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-adservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/adservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-shoppingassistantservice-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/shoppingassistantservice
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-loadgenerator-dev
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/dev/loadgenerator
  dependsOn:
    - name: tenant-boutique-dev
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-frontend-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/frontend
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-cartservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/cartservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-checkoutservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/checkoutservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-currencyservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/currencyservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-emailservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/emailservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-paymentservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/paymentservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-productcatalogservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/productcatalogservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-recommendationservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/recommendationservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-shippingservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/shippingservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-adservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/adservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-shoppingassistantservice-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/shoppingassistantservice
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-boutique-loadgenerator-prod
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-blueprint
  path: ./k8s/apps/boutique-app/prod/loadgenerator
  dependsOn:
    - name: tenant-boutique-prod
  wait: true
  timeout: 3m
