apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: platform-app-service-chart
  namespace: flux-system
spec:
  interval: 10m
  url: "oci://craksplatformsea001.azurecr.io/helm/platform-app-service"
  ref:
    semver: ">=0.1.0"
  secretRef:
    name: acr-oci-auth
