service:
  name: productcatalogservice

nameOverride: productcatalogservice

image:
  repository: craksplatformsea001.azurecr.io/boutique/productcatalogservice
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

container:
  port: 3550

serviceAccount:
  create: true
  name: productcatalogservice
  workloadIdentity:
    enabled: true
    clientId: ""

platform:
  tenant: boutique
  app: boutique-app
  environment: dev
  keyVaultUrl: ""
  appSettings:
    enabled: true
    existingConfigMap: productcatalogservice-app-settings
    mountPath: /app/config/app-settings.json

route:
  enabled: false
  gatewayName: shared-public
  gatewayNamespace: gateway-system
  hostnames:
    - boutique-app-dev.example.com

nodeSelector:
  aks-platform.azure.com/node-purpose: app-workload
  aks-platform.azure.com/capacity: on-demand
tolerations:
  - key: workload
    operator: Equal
    value: app-workload
    effect: NoSchedule
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: productcatalogservice

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
