apiVersion: v1
kind: Namespace
metadata:
  name: tenant-boutique-dev
  labels:
    tenant: boutique
    app: boutique-app
    environment: dev
    data-classification: internal
    shared-gateway-access: "true"
