apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingassistantservice-app-settings
  namespace: tenant-boutique-dev
  labels:
    tenant: boutique
    app: boutique-app
    service: shoppingassistantservice
    environment: dev
data:
  app-settings.json: |
    {
      "schemaVersion": "platform.settings/v1",
      "platform": {
        "tenant": "boutique",
        "app": "boutique-app",
        "service": "shoppingassistantservice",
        "environment": "dev"
      },
      "keyVault": {
        "urlEnv": "PLATFORM_KEY_VAULT_URL",
        "secretMappings": [
          {
            "name": "appInsights",
            "env": "APPLICATIONINSIGHTS_CONNECTION_STRING",
            "secretName": "boutique-dev-appinsights-connection-string",
            "required": true
          }
        ]
      },
      "dependencies": {
        "services": {
          "productcatalogservice": {
            "url": "http://productcatalogservice:3550"
          }
        }
      },
      "features": {
      }
    }
